
name: Deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  EMSDK_VER: 3.1.42
  EMSDK_CACHE: 'emsdk-cache'
  EMSDK_ROOT: '$GITHUB_WORKSPACE/$EMSDK_CACHE/emsdk-main/upstream/emscripten'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{ env.EMSDK_CACHE }}
        key: ${{ env.EMSDK_VER }}-${{ runner.os }}
        
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ env.EMSDK_VER }}
        actions-cache-folder: ${{ env.EMSDK_CACHE }}
        
    - name: Tell me the truth
      run: ls -la ${{ env.EMSDK_ROOT }}
  
    - name: CMake Configure
      run: cmake --preset emscripten-release
  
    - name: CMake Build
      run: cmake --build out/build/emscripten-release --parallel 4
  
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: "out/build/emscripten-release/src/"

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy pages
      uses: actions/deploy-pages@v2
